dist: xenial
language: node_js
node_js:
  - "11"
  - "10"
  - "9"
  - "8"

install:
  - npm install

deploy:
  provider: script
  script: "cp .npmrc.template $HOME/.npmrc && npm publish"
  skip_cleanup: true
  on:
    node: 10
    tags: true

notifications:
  irc: "ircs://irc.androidirc.org:6697/#duwww"
